### ISSUE TITLE
NoGrid error

### ISSUE THREAD

**Issue by shikulja** [laytya/Lazyspell#2]
same, lazy spell does not get the correct rank spell
![WoWScrnShot_071019_140225_cr](https://user-images.githubusercontent.com/3386359/60964462-0a603600-a31c-11e9-9144-67b5d55d09dd.png)

nogrid core.lua 234

> if LazySpell then --_LazySpell quick and dirty fix
> 			local lsSpell,lsRank = LazySpell:ExtractSpell(foundspell)
> 			if self.HealComm.Spells[lsSpell] and lsRank == 1 then
> 				local lsRank = LazySpell:CalculateRank(lsSpell, this.unit)
> 				foundspell = lsSpell.."(Rank "..lsRank..")"
> 			end
> 		end

**Comment by shikulja** [comment]
![Honeyview_agUF](https://user-images.githubusercontent.com/3386359/60960805-70948b00-a313-11e9-93ef-62baaaae48a4.jpg)
![Honeyview_nogrid](https://user-images.githubusercontent.com/3386359/60960806-70948b00-a313-11e9-9030-be4a3c6f33f3.jpg)

debug mode with nogrid doesn't work either

**Comment by laytya** [comment]
I added 2 new function to help integration w/ other addons...

function LazySpell:ValidateSpell(spell,unit)

returns the full name of the modified spell
or old spell value if not matched


LazySpell:GetSmartSpell(spell, unit)

returns the modified rank or nil if the spell is not supported
