### ISSUE TITLE
Does not work with other localizations.

### ISSUE THREAD

**Issue by shikulja** [laytya/Lazyspell#3]
lazy spell seems work, but say error all time
![WoWScrnShot_070919_215505_cr](https://user-images.githubusercontent.com/3386359/61225804-fbb5bc80-a729-11e9-8418-7b63753ecc95.png)
on nogrid and luna same error

For testing can help EN \ RU WoW client, works on elizium
[https://wowruru.github.io/win_instruction.html](url)

**Comment by laytya** [comment]
Библиотеки нужно подменить которые подходят

**Comment by shikulja** [comment]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/3386359/185705236-0b65e328-2d23-4991-b239-220cc1b8dffc.png">

Нет, и с встроенными в 0.4 ошибка, и с моими (в принципе теже)
но с pfquest теперь работает
